docker-library/php

5.4/apache/apache2.conf
5.5/apache/apache2.conf
5.6/apache/apache2.conf

Fixes https://github.com/docker-library/wordpress/issues/33

Remove Indexes option from /var/www

---

5.4/Dockerfile
5.4/apache/Dockerfile
5.4/fpm/Dockerfile
5.5/Dockerfile
5.5/apache/Dockerfile
5.5/fpm/Dockerfile
5.6/Dockerfile
5.6/apache/Dockerfile
5.6/fpm/Dockerfile

I just discovered today that `autoremove` doesn't remove packages that are required *or* suggested by any installed package, even if the package that auto-installed them gets removed.
I ended up adding `-o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false` in jwilder/docker-gen#66 to get `apt-get` to remove additional packages that it wasn't removing otherwise.
I'm sure there are other images where this change would make sense, but I thought I'd start with `php`.

Tell apt-get to actually autoremove everything it should

---

5.4/Dockerfile
5.4/apache/Dockerfile
5.4/fpm/Dockerfile
5.5/Dockerfile
5.5/apache/Dockerfile
5.5/fpm/Dockerfile
5.6/Dockerfile
5.6/apache/Dockerfile
5.6/fpm/Dockerfile

Looks like the changes related to `--auto-remove` in #71 had the inadvertent side effect of breaking `docker-php-ext-install`. This patch explicitly adds back `libc-dev` as a dependency, but another option in this case might be to simply revert #71.
The reason I did the former instead of the latter is that I still think that the `APT::AutoRemove::RecommendsImportant=false` pattern is a good one in general since it can prevent packages from getting left in an image inadvertently. That being said, in the case of the `php:*` images, the end result would be the same.

Add libc-dev as an explicit phpize dependency

---

5.4/Dockerfile
5.4/apache/Dockerfile
5.4/fpm/Dockerfile
5.5/Dockerfile
5.5/apache/Dockerfile
5.5/fpm/Dockerfile
5.6/Dockerfile
5.6/apache/Dockerfile
5.6/fpm/Dockerfile

This change prevents tar from preserving file ownership metadata when it extracts the PHP source archives. This allows containers based on these images to be installed on Circle CI build containers which are LXC containers with restricted UID ranges.

Prevent tar preserving file ownership

---

5.4/Dockerfile
5.4/apache/Dockerfile
5.4/fpm/Dockerfile
5.5/Dockerfile
5.5/apache/Dockerfile
5.5/fpm/Dockerfile
5.6/Dockerfile
5.6/apache/Dockerfile
5.6/fpm/Dockerfile

file is still needed for docker-php-install-ext.

Remove file from buildDeps

---

5.4/Dockerfile
5.4/apache/Dockerfile
5.4/fpm/Dockerfile
5.5/Dockerfile
5.5/apache/Dockerfile
5.5/fpm/Dockerfile
5.6/Dockerfile
5.6/apache/Dockerfile
5.6/fpm/Dockerfile

phpize in docker-php-ext-install would fail if it cannot find config.m4. Some modules, such as zlib, sqlite3 use the name cnofig0.m4 instead of config.m4. This commit performs auto renaming after php is installed.

Rename config0.m4 to config.m4 to avoid phpize failure

---

5.4/fpm/php-fpm.conf
5.5/fpm/php-fpm.conf
5.6/fpm/php-fpm.conf

Allows php scripts executed with FPM to access env vars such as env vars
from linked containers
see #74

Tells FPM not to clear the environment in workers

---

5.4/Dockerfile
5.4/apache/Dockerfile
5.4/fpm/Dockerfile
5.5/Dockerfile
5.5/apache/Dockerfile
5.5/fpm/Dockerfile
5.6/Dockerfile
5.6/apache/Dockerfile
5.6/fpm/Dockerfile

As announced here;
PHP 5.4.43 http://php.net/archive/2015.php#id2015-07-09-1
PHP 5.5.27 http://php.net/archive/2015.php#id2015-07-10-2
PHP 5.6.11 http://php.net/archive/2015.php#id2015-07-10-3
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

Update to 5.4.43, 5.5.27, and 5.6.11

---

5.4/apache/docker-php-ext-enable
5.4/apache/docker-php-ext-install
5.4/docker-php-ext-enable
5.4/docker-php-ext-install
5.4/fpm/docker-php-ext-enable
5.4/fpm/docker-php-ext-install
5.5/apache/docker-php-ext-enable
5.5/apache/docker-php-ext-install
5.5/docker-php-ext-enable
5.5/docker-php-ext-install
5.5/fpm/docker-php-ext-enable
5.5/fpm/docker-php-ext-install
5.6/apache/docker-php-ext-enable
5.6/apache/docker-php-ext-install
5.6/docker-php-ext-enable
5.6/docker-php-ext-install
5.6/fpm/docker-php-ext-enable
5.6/fpm/docker-php-ext-install
7.0/apache/docker-php-ext-enable
7.0/apache/docker-php-ext-install
7.0/docker-php-ext-enable
7.0/docker-php-ext-install
7.0/fpm/docker-php-ext-enable
7.0/fpm/docker-php-ext-install
docker-php-ext-enable
docker-php-ext-install

This also updates `docker-php-ext-install` to invoke this script properly after successful extension compilation.
If modules are determined to already be enabled, it'll skip them appropriately.
This removes simple warnings like `PHP Warning:  Module 'curl' already loaded in Unknown on line 0`, and enables things like `pecl install mongo && docker-php-ext-enable mongo`.
Fixes https://github.com/docker-library/php/issues/102
Fixes https://github.com/docker-library/drupal/pull/5

Add new "docker-php-ext-enable" script for more intelligent module enabling

---

5.4/apache/docker-php-ext-enable
5.4/docker-php-ext-enable
5.4/fpm/docker-php-ext-enable
5.5/apache/docker-php-ext-enable
5.5/docker-php-ext-enable
5.5/fpm/docker-php-ext-enable
5.6/apache/docker-php-ext-enable
5.6/docker-php-ext-enable
5.6/fpm/docker-php-ext-enable
7.0/apache/docker-php-ext-enable
7.0/docker-php-ext-enable
7.0/fpm/docker-php-ext-enable
docker-php-ext-enable

On loading zend extensions PHP requires full path to extension

Full path for loading zend extensions

---

5.4/Dockerfile
5.4/apache/Dockerfile
5.4/fpm/Dockerfile
5.5/Dockerfile
5.5/apache/Dockerfile
5.5/fpm/Dockerfile
5.6/Dockerfile
5.6/apache/Dockerfile
5.6/fpm/Dockerfile
7.0/Dockerfile
7.0/apache/Dockerfile
7.0/fpm/Dockerfile

See [previous builds](https://travis-ci.org/docker-library/php/jobs/83337124#L694).
Any way, [no external libraries are needed to build PCRE](http://php.net/manual/en/pcre.requirements.php) and [it is a core PHP extension](http://php.net/manual/en/pcre.installation.php) so the installation of libpcre3-dev is optional.

--with-pcre is not a valid configure option

---

5.5/apache/docker-php-ext-install
5.5/docker-php-ext-install
5.5/fpm/docker-php-ext-install
5.6/apache/docker-php-ext-install
5.6/docker-php-ext-install
5.6/fpm/docker-php-ext-install
7.0/apache/docker-php-ext-install
7.0/docker-php-ext-install
7.0/fpm/docker-php-ext-install
docker-php-ext-install

Allow a "-j" or "--jobs" argument to "docker-php-ext-install" to speed up extension building

---

5.5/Dockerfile
5.5/apache/Dockerfile
5.5/fpm/Dockerfile
5.5/zts/Dockerfile
5.6/Dockerfile
5.6/apache/Dockerfile
5.6/fpm/Dockerfile
5.6/zts/Dockerfile
7.0/Dockerfile
7.0/apache/Dockerfile
7.0/fpm/Dockerfile
7.0/zts/Dockerfile

PHP 7.0.4, 5.6.19 and 5.5.33 released.
http://php.net/downloads.php

Update to 7.0.4, 5.6.19, and 5.5.33

---

5.5/Dockerfile
5.5/alpine/Dockerfile
5.5/apache/Dockerfile
5.5/fpm/Dockerfile
5.5/fpm/alpine/Dockerfile
5.5/zts/Dockerfile
5.5/zts/alpine/Dockerfile
5.6/Dockerfile
5.6/alpine/Dockerfile
5.6/apache/Dockerfile
5.6/fpm/Dockerfile
5.6/fpm/alpine/Dockerfile
5.6/zts/Dockerfile
5.6/zts/alpine/Dockerfile
7.0/Dockerfile
7.0/alpine/Dockerfile
7.0/apache/Dockerfile
7.0/fpm/Dockerfile
7.0/fpm/alpine/Dockerfile
7.0/zts/Dockerfile
7.0/zts/alpine/Dockerfile
Dockerfile-alpine.template
Dockerfile-debian.template

Explicitly enable "mbstring" by default (since certain pecl bits cannot work properly otherwise)

---

5.5/alpine/Dockerfile
5.6/alpine/Dockerfile
7.0/alpine/Dockerfile
Dockerfile-alpine.template

Adds `--no-cache` to the final `apk add` in the `Dockerfile`. The other `apk add`'s already have this flag; however the cache is currently created anyway because of the final `apk add`.

Avoid cache in Alpine apk add

---

Dockerfile-alpine.template
Dockerfile-debian.template
docker-php-ext-configure
docker-php-ext-install
docker-php-source
update.sh

Builds upon and closes #245.  Thanks to @shouze for all his work on this.  I was debugging his changes and decided that it would be clearer to add my improvements on top.
Fixes #234.

Remove extracted php src

---

Dockerfile-alpine.template
Dockerfile-debian.template

My specific use-case is one where I'm trying to run php-pm in a Docker container, however it has a hard dependency on CGI.  Unfortunately `--enable-cgi` doesn't work as an additional parameter in my Dockerfile, as the line immediately after it is `--disable-cgi`!

Shuffling around order so as to override default configure options.

---

5.5/apache/Dockerfile
5.6/apache/Dockerfile
7.0/apache/Dockerfile
apache-Dockerfile-block-1

This is intended as something to think about and discuss first, which is why I've not run `update.sh` yet. :smile:
The intended use case is to allow for these pre-provided environment variables which are currently hard-coded and can only be changed by modifying this `envvars` file to be easily user-specifiable via `-e` on the `docker run` command line.
Before:
```sh
unset HOME
if [ "${APACHE_CONFDIR##/etc/apache2-}" != "${APACHE_CONFDIR}" ] ; then
SUFFIX="-${APACHE_CONFDIR##/etc/apache2-}"
else
SUFFIX=
fi
export APACHE_RUN_USER=www-data
export APACHE_RUN_GROUP=www-data
export APACHE_PID_FILE=/var/run/apache2/apache2$SUFFIX.pid
export APACHE_RUN_DIR=/var/run/apache2$SUFFIX
export APACHE_LOCK_DIR=/var/lock/apache2$SUFFIX
export APACHE_LOG_DIR=/var/log/apache2$SUFFIX
export LANG=C
export …
```

Convert explicit "export A=B" lines of Apache's envvars file into "${A:=B}" such that we can override them at runtime easily

---

Dockerfile-alpine.template
Dockerfile-debian.template

`ftp_ssl_connect()` needs ftp to be built statically into PHP #236

enable ftp by default

---

5.6/apache/apache2-foreground
7.0/apache/apache2-foreground
7.1/apache/apache2-foreground

Fix #250
Signed-off-by: Tao Wang <twang2218@gmail.com>

Setup the `$APACHE_RUN_DIR` and `$APACHE_LOCK_DIR` directories in runtime

---

5.6/alpine/docker-php-ext-enable
5.6/apache/docker-php-ext-enable
5.6/docker-php-ext-enable
5.6/fpm/alpine/docker-php-ext-enable
5.6/fpm/docker-php-ext-enable
5.6/zts/alpine/docker-php-ext-enable
5.6/zts/docker-php-ext-enable
7.0/alpine/docker-php-ext-enable
7.0/apache/docker-php-ext-enable
7.0/docker-php-ext-enable
7.0/fpm/alpine/docker-php-ext-enable
7.0/fpm/docker-php-ext-enable
7.0/zts/alpine/docker-php-ext-enable
7.0/zts/docker-php-ext-enable
7.1/alpine/docker-php-ext-enable
7.1/apache/docker-php-ext-enable
7.1/docker-php-ext-enable
7.1/fpm/alpine/docker-php-ext-enable
7.1/fpm/docker-php-ext-enable
7.1/zts/alpine/docker-php-ext-enable
7.1/zts/docker-php-ext-enable
docker-php-ext-enable

This matches the behavior of `docker-php-ext-configure` and `docker-php-ext-install`, and ensures that `nm` is installed and then removed in Alpine where necessary.
Closes #417
Closes #419

Install "binutils" in "docker-php-ext-enable" if needed

---

5.6/Dockerfile
5.6/alpine/Dockerfile
5.6/apache/Dockerfile
5.6/fpm/Dockerfile
5.6/fpm/alpine/Dockerfile
5.6/zts/Dockerfile
5.6/zts/alpine/Dockerfile
7.0/Dockerfile
7.0/alpine/Dockerfile
7.0/apache/Dockerfile
7.0/fpm/Dockerfile
7.0/fpm/alpine/Dockerfile
7.0/zts/Dockerfile
7.0/zts/alpine/Dockerfile
7.1/Dockerfile
7.1/alpine/Dockerfile
7.1/apache/Dockerfile
7.1/fpm/Dockerfile
7.1/fpm/alpine/Dockerfile
7.1/zts/Dockerfile
7.1/zts/alpine/Dockerfile
Dockerfile-alpine.template
Dockerfile-debian.template

After #429 was merged, `pcre-dev` library is required to install any PHP extension: it doesn't matter if the extension is provided with PHP source or not (eg. #432 )
Fixes #432

Add pcre-dev library to PHPize dependency list

---

5.6/Dockerfile
5.6/alpine/Dockerfile
5.6/apache/Dockerfile
5.6/fpm/Dockerfile
5.6/fpm/alpine/Dockerfile
5.6/zts/Dockerfile
5.6/zts/alpine/Dockerfile
7.0/Dockerfile
7.0/alpine/Dockerfile
7.0/apache/Dockerfile
7.0/fpm/Dockerfile
7.0/fpm/alpine/Dockerfile
7.0/zts/Dockerfile
7.0/zts/alpine/Dockerfile
7.1/Dockerfile
7.1/alpine/Dockerfile
7.1/apache/Dockerfile
7.1/fpm/Dockerfile
7.1/fpm/alpine/Dockerfile
7.1/zts/Dockerfile
7.1/zts/alpine/Dockerfile
Dockerfile-alpine.template
Dockerfile-debian.template

Explicitly invoke "pecl update-channels" at build time to ensure our channel definitions are up-to-date

---

5.6/Dockerfile
5.6/apache/Dockerfile
5.6/fpm/Dockerfile
5.6/zts/Dockerfile
7.0/Dockerfile
7.0/apache/Dockerfile
7.0/fpm/Dockerfile
7.0/zts/Dockerfile
7.1/Dockerfile
7.1/apache/Dockerfile
7.1/fpm/Dockerfile
7.1/zts/Dockerfile
Dockerfile-debian.template

```
DEB_BUILD_GNU_TYPE=i586-linux-gnu
DEB_BUILD_MULTIARCH=i386-linux-gnu
```

Account for DEB_BUILD_MULTIARCH vs DEB_BUILD_GNU_TYPE disparity

---

generate-stackbrew-library.sh

```
/usr/src/php/ext/hash/sha3/generic64lc/KeccakP-1600-opt64.c: In function 'KeccakP1600_AddLanes':
/usr/src/php/ext/hash/sha3/generic64lc/KeccakP-1600-opt64.c:158:22: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
UINT8 *curData = data;
^~~~
/usr/src/php/ext/hash/sha3/generic64lc/KeccakP-1600-opt64.c: In function 'KeccakP1600_OverwriteBytesInLane':
/usr/src/php/ext/hash/sha3/generic64lc/KeccakP-1600-opt64.c:208:2: error: #error "Not yet implemented"
#error "Not yet implemented"
^~~~~
/usr/src/php/ext/hash/sha3/generic64lc/KeccakP-1600-opt64.c: In function 'KeccakP1600_OverwriteLanes':
/usr/src/php/ext/hash/sha3/generic64lc/KeccakP-1600-opt64.c:229:2: error: #error "Not yet implemented"
#error "Not yet implemented"
^~~~~ …
```

Remove s390x from 7.2+

---

generate-stackbrew-library.sh

See also docker-library/ruby#151, https://github.com/docker-library/python/pull/220.

Remove support for arm32v5 (takes too long to build)

---

5.6/alpine/Dockerfile
5.6/fpm/alpine/Dockerfile
5.6/zts/alpine/Dockerfile
7.0/alpine/Dockerfile
7.0/fpm/alpine/Dockerfile
7.0/zts/alpine/Dockerfile
7.1/alpine/Dockerfile
7.1/fpm/alpine/Dockerfile
7.1/zts/alpine/Dockerfile
7.2-rc/alpine/Dockerfile
7.2-rc/fpm/alpine/Dockerfile
7.2-rc/zts/alpine/Dockerfile
Dockerfile-alpine.template
update.sh

Update Alpine 3.6+ to use "libressl" instead of "openssl"

---

5.6/alpine/Dockerfile
5.6/fpm/alpine/Dockerfile
5.6/zts/alpine/Dockerfile
7.0/alpine/Dockerfile
7.0/fpm/alpine/Dockerfile
7.0/zts/alpine/Dockerfile
7.1/alpine/Dockerfile
7.1/fpm/alpine/Dockerfile
7.1/zts/alpine/Dockerfile
7.2-rc/alpine/Dockerfile
7.2-rc/fpm/alpine/Dockerfile
7.2-rc/zts/alpine/Dockerfile
Dockerfile-alpine.template

Copying the improvement from https://github.com/docker-library/ruby/pull/161.  Should be no discernible change in packages installed, but does make the sub-shell a little easier to understand.

Adjust scanelf to properly detect runDeps

---

7.2-rc/stretch/apache/Dockerfile
7.2-rc/stretch/cli/Dockerfile
7.2-rc/stretch/fpm/Dockerfile
7.2-rc/stretch/zts/Dockerfile
Dockerfile-debian.template
update.sh

See https://wiki.php.net/rfc/argon2_password_hash
See also https://gitlab.com/deb.sury.org/php/commit/a91992745b62690ef5257cd6597ad0a8d7afe9ff
Closes #515
Technically we can also consider this for Alpine 3.7+ (since they have an `argon2-dev` package in Edge currently), which I've noted in a comment in `update.sh`.

Add Argon2 password hashing

---

5.6/alpine3.4/cli/Dockerfile
5.6/alpine3.4/fpm/Dockerfile
5.6/alpine3.4/zts/Dockerfile
5.6/jessie/apache/Dockerfile
5.6/jessie/cli/Dockerfile
5.6/jessie/fpm/Dockerfile
5.6/jessie/zts/Dockerfile
7.0/alpine3.4/cli/Dockerfile
7.0/alpine3.4/fpm/Dockerfile
7.0/alpine3.4/zts/Dockerfile
7.0/jessie/apache/Dockerfile
7.0/jessie/cli/Dockerfile
7.0/jessie/fpm/Dockerfile
7.0/jessie/zts/Dockerfile
7.1/alpine3.4/cli/Dockerfile
7.1/alpine3.4/fpm/Dockerfile
7.1/alpine3.4/zts/Dockerfile
7.1/jessie/apache/Dockerfile
7.1/jessie/cli/Dockerfile
7.1/jessie/fpm/Dockerfile
7.1/jessie/zts/Dockerfile
7.2-rc/alpine3.6/cli/Dockerfile
7.2-rc/alpine3.6/fpm/Dockerfile
7.2-rc/alpine3.6/zts/Dockerfile
7.2-rc/stretch/apache/Dockerfile
7.2-rc/stretch/cli/Dockerfile
7.2-rc/stretch/fpm/Dockerfile
7.2-rc/stretch/zts/Dockerfile
Dockerfile-alpine.template
Dockerfile-debian.template

Fixes #495.  Thanks to @GordonHarley's [comment](https://github.com/docker-library/php/issues/495#issuecomment-347063664).
I've successfully built this on s390x. :tada:

Use bundled pcre and disable pcre-jit on unsupported platforms

---

5.6/alpine3.4/cli/docker-php-ext-enable
5.6/alpine3.4/fpm/docker-php-ext-enable
5.6/alpine3.4/zts/docker-php-ext-enable
5.6/jessie/apache/docker-php-ext-enable
5.6/jessie/cli/docker-php-ext-enable
5.6/jessie/fpm/docker-php-ext-enable
5.6/jessie/zts/docker-php-ext-enable
7.0/alpine3.4/cli/docker-php-ext-enable
7.0/alpine3.4/fpm/docker-php-ext-enable
7.0/alpine3.4/zts/docker-php-ext-enable
7.0/jessie/apache/docker-php-ext-enable
7.0/jessie/cli/docker-php-ext-enable
7.0/jessie/fpm/docker-php-ext-enable
7.0/jessie/zts/docker-php-ext-enable
7.1/alpine3.4/cli/docker-php-ext-enable
7.1/alpine3.4/fpm/docker-php-ext-enable
7.1/alpine3.4/zts/docker-php-ext-enable
7.1/jessie/apache/docker-php-ext-enable
7.1/jessie/cli/docker-php-ext-enable
7.1/jessie/fpm/docker-php-ext-enable
7.1/jessie/zts/docker-php-ext-enable
7.2/alpine3.6/cli/docker-php-ext-enable
7.2/alpine3.6/fpm/docker-php-ext-enable
7.2/alpine3.6/zts/docker-php-ext-enable
7.2/stretch/apache/docker-php-ext-enable
7.2/stretch/cli/docker-php-ext-enable
7.2/stretch/fpm/docker-php-ext-enable
7.2/stretch/zts/docker-php-ext-enable
docker-php-ext-enable

See also https://github.com/docker-library/php/pull/420#issuecomment-349372144 and the following discussion.

Switch from "nm" to "readelf" so that we can detect the "zend_extension_entry" symbol even in stripped objects

---

5.6/jessie/apache/Dockerfile
5.6/jessie/cli/Dockerfile
5.6/jessie/fpm/Dockerfile
5.6/jessie/zts/Dockerfile
7.0/jessie/apache/Dockerfile
7.0/jessie/cli/Dockerfile
7.0/jessie/fpm/Dockerfile
7.0/jessie/zts/Dockerfile
7.1/jessie/apache/Dockerfile
7.1/jessie/cli/Dockerfile
7.1/jessie/fpm/Dockerfile
7.1/jessie/zts/Dockerfile
7.2/stretch/apache/Dockerfile
7.2/stretch/cli/Dockerfile
7.2/stretch/fpm/Dockerfile
7.2/stretch/zts/Dockerfile
Dockerfile-debian.template

This will hopefully help folks with the confusion around installing packages like "php-apcu" and then wondering why they don't actually "work" (because they pull in Debian's PHP, and that's not what this image packages).

Block the installation of Debian's PHP packages

---

5.6/alpine3.4/fpm/Dockerfile
5.6/jessie/fpm/Dockerfile
7.0/alpine3.4/fpm/Dockerfile
7.0/jessie/fpm/Dockerfile
7.1/alpine3.4/fpm/Dockerfile
7.1/jessie/fpm/Dockerfile
7.2/alpine3.6/fpm/Dockerfile
7.2/alpine3.7/fpm/Dockerfile
7.2/stretch/fpm/Dockerfile
fpm-Dockerfile-block-2

In PHP 7.2.1 [a change][] was made in response to bug [#74166][] to fall back to listening on 0.0.0.0 if IPv6 is disabled (for example with `ipv6.disable=1` Linux kernel param) instead of failing to create a listening socket with the error "Address family not supported by protocol (97)".
A fallback to IPv4 in such circumstances is only possible in PHP >= 7.2.1 and by specifying a port number without an address to the `listen` directive.
It isn't clear to me how to update the Dockerfiles with this template change, but am happy to do so if pointed in the right direction.
[a change]: https://github.com/php/php-src/commit/b63c45c69e3a97b05314c6f3328a0ff695e28d36
[#74166]: https://bugs.php.net/bug.php?id=74166 "IPv6 forced to be enabled"

Allow FPM pool to listen on IPv4 when IPv6 is disabled

---

7.2/alpine3.6/cli/Dockerfile
7.2/alpine3.6/fpm/Dockerfile
7.2/alpine3.6/zts/Dockerfile
7.2/alpine3.7/cli/Dockerfile
7.2/alpine3.7/fpm/Dockerfile
7.2/alpine3.7/zts/Dockerfile
7.2/stretch/apache/Dockerfile
7.2/stretch/cli/Dockerfile
7.2/stretch/fpm/Dockerfile
7.2/stretch/zts/Dockerfile
Dockerfile-alpine.template
Dockerfile-debian.template
update.sh

Add libsodium to 7.2+

---

7.3-rc/alpine3.8/fpm/Dockerfile
7.3-rc/stretch/fpm/Dockerfile
fpm-Dockerfile-block-2
update.sh

As of PHP 7.3 we can finally use STDOUT and STDERR properly in our containers, this disables the `[pool %s] child %d said into %s: \"%s\` format.
More info:
- https://github.com/php/php-src/pull/2458
- https://bugs.php.net/bug.php?id=71880
- https://github.com/docker-library/php/issues/207

Remove log decoration from workers output

---

5.6/jessie/apache/Dockerfile
5.6/stretch/apache/Dockerfile
7.0/jessie/apache/Dockerfile
7.0/stretch/apache/Dockerfile
7.1/jessie/apache/Dockerfile
7.1/stretch/apache/Dockerfile
7.2/stretch/apache/Dockerfile
7.3-rc/stretch/apache/Dockerfile
apache-Dockerfile-block-1

Tested successfully with both of (separately) `--user x:y --sysctl ...` and `-e APACHE_RUN_USER=x -e APACHE_RUN_GROUP=y` (and without any parameters, of course).
Fixes #754
Refs #745, #743

Fix Apache "log directory" permissions for arbitrary user support

---

7.4-rc/alpine3.10/cli/Dockerfile
7.4-rc/alpine3.10/fpm/Dockerfile
7.4-rc/alpine3.10/zts/Dockerfile
7.4-rc/alpine3.9/cli/Dockerfile
7.4-rc/alpine3.9/fpm/Dockerfile
7.4-rc/alpine3.9/zts/Dockerfile
Dockerfile-alpine.template
update.sh

hello, the fix has been patched upstream in Alpine v3.9 and v3.10 and upcoming PHP 7.4.0alpha2.
Thanks.

Remove the Alpine argon2 library fix

---

7.4-rc/alpine3.10/cli/Dockerfile
7.4-rc/alpine3.10/fpm/Dockerfile
7.4-rc/alpine3.10/zts/Dockerfile
7.4-rc/alpine3.9/cli/Dockerfile
7.4-rc/alpine3.9/fpm/Dockerfile
7.4-rc/alpine3.9/zts/Dockerfile
7.4-rc/stretch/apache/Dockerfile
7.4-rc/stretch/cli/Dockerfile
7.4-rc/stretch/fpm/Dockerfile
7.4-rc/stretch/zts/Dockerfile
Dockerfile-alpine.template
Dockerfile-debian.template
update.sh

This means that `pear` and `pecl` will be available for PHP 7.4+, but *will be removed* in PHP 8+ (see https://externals.io/message/103977 for upstream discussion around this deprecation).
I tested the 8+ changes to this script by creating a few fake "8.0" bits in the script itself (fake `possibles` version, etc) and verified that the result is as expected.
Closes #846

Add "--with-pear" in 7.4

---

7.2/alpine3.10/cli/Dockerfile
7.2/alpine3.10/fpm/Dockerfile
7.2/alpine3.10/zts/Dockerfile
7.2/alpine3.9/cli/Dockerfile
7.2/alpine3.9/fpm/Dockerfile
7.2/alpine3.9/zts/Dockerfile
7.2/buster/apache/Dockerfile
7.2/buster/cli/Dockerfile
7.2/buster/fpm/Dockerfile
7.2/buster/zts/Dockerfile
7.2/stretch/apache/Dockerfile
7.2/stretch/cli/Dockerfile
7.2/stretch/fpm/Dockerfile
7.2/stretch/zts/Dockerfile
7.3/alpine3.10/cli/Dockerfile
7.3/alpine3.10/fpm/Dockerfile
7.3/alpine3.10/zts/Dockerfile
7.3/alpine3.9/cli/Dockerfile
7.3/alpine3.9/fpm/Dockerfile
7.3/alpine3.9/zts/Dockerfile
7.3/buster/apache/Dockerfile
7.3/buster/cli/Dockerfile
7.3/buster/fpm/Dockerfile
7.3/buster/zts/Dockerfile
7.3/stretch/apache/Dockerfile
7.3/stretch/cli/Dockerfile
7.3/stretch/fpm/Dockerfile
7.3/stretch/zts/Dockerfile

Making this PR manually given that 7.4.0RC2 is gumming up our builder ATM (https://github.com/docker-library/php/issues/882#issuecomment-533305377).
I believe there's at least going to be a 7.2 release as well (from commits/tags on https://github.com/php/php-src), but it doesn't appear to be available yet.

[security] Update to 7.3.10

---

generate-stackbrew-library.sh

fixes https://github.com/docker-library/php/issues/984
reverts https://github.com/docker-library/php/pull/487
It looks like the fix was in https://github.com/php/php-src/pull/2789.
:balloon: :tada:

Add back s390x builds

---

generate-stackbrew-library.sh

Just to have it also written down somewhere, here's the full error:
```console
In file included from /usr/src/php/ext/pcre/pcrelib/sljit/sljitLir.c:1747,
from /usr/src/php/ext/pcre/pcrelib/pcre_jit_compile.c:62:
/usr/src/php/ext/pcre/pcrelib/sljit/sljitNativeMIPS_common.c: In function 'sljit_has_cpu_feature':
/usr/src/php/ext/pcre/pcrelib/sljit/sljitNativeMIPS_common.c:506:3: error: a label can only be part of a statement and a declaration is not a statement
sljit_sw fir;
^~~~~~~~
make: *** [Makefile:670: ext/pcre/pcrelib/pcre_jit_compile.lo] Error 1
make: *** Waiting for unfinished jobs....
```
See the comments in the code for more details.

Exclude mips64le from 7.2

---

8.0-rc/alpine3.12/cli/Dockerfile
8.0-rc/alpine3.12/fpm/Dockerfile
8.0-rc/buster/apache/Dockerfile
8.0-rc/buster/cli/Dockerfile
8.0-rc/buster/fpm/Dockerfile
8.0-rc/buster/zts/Dockerfile

Release notes: https://www.php.net/archive/2020.php#2020-07-09-1
Manifest: https://gist.github.com/carusogabriel/0ae8a6238ab9336be7d8e1eb6873888f
Question: where is the documentation on how to run `./update.sh`?

Update to PHP 8.0.0alpha2

---

8.0-rc/alpine3.12/cli/Dockerfile
8.0-rc/alpine3.12/fpm/Dockerfile
8.0-rc/buster/apache/Dockerfile
8.0-rc/buster/cli/Dockerfile
8.0-rc/buster/fpm/Dockerfile
8.0-rc/buster/zts/Dockerfile

Release Notes:
https://www.php.net/archive/2020.php#2020-07-23-1
Download-Repository:
https://downloads.php.net/~carusogabriel/
Manifest:
https://gist.github.com/carusogabriel/6e0b8b33ee4dd2da23002863af4de965

Updating php from alpha2 to alpha3

---

7.4/alpine3.11/cli/Dockerfile
7.4/alpine3.11/fpm/Dockerfile
7.4/alpine3.11/zts/Dockerfile
7.4/alpine3.12/cli/Dockerfile
7.4/alpine3.12/fpm/Dockerfile
7.4/alpine3.12/zts/Dockerfile
7.4/buster/apache/Dockerfile
7.4/buster/cli/Dockerfile
7.4/buster/fpm/Dockerfile
7.4/buster/zts/Dockerfile
8.0-rc/alpine3.12/cli/Dockerfile
8.0-rc/alpine3.12/fpm/Dockerfile
8.0-rc/buster/apache/Dockerfile
8.0-rc/buster/cli/Dockerfile
8.0-rc/buster/fpm/Dockerfile
8.0-rc/buster/zts/Dockerfile
Dockerfile-alpine.template
Dockerfile-debian.template

Resolves #1087 
It appears that pear/pecl are not removed in PHP 8.0. Indeed, even the PHP 8.0 changelog mentions needing to install xml-rpc using pecl as of 8.0:
https://www.php.net/manual/en/migration80.incompatible.php#migration80.incompatible.xmlrpc
This means that PHP 7.4 and 8+ can both use the `--with-pear` option.

Configure PHP with pear/pecl installers for PHP 8.0

---

7.3/buster/cli/Dockerfile
7.3/stretch/cli/Dockerfile
7.4/buster/cli/Dockerfile
8.0/buster/cli/Dockerfile
Dockerfile-cli-block-1.template

This is used for things like NGINX Unit to embed PHP (similar to `mod_php` in Apache, but a more general interface).
See https://github.com/docker-library/php/pull/939#issuecomment-730501748
Closes #939
(FYI/cc @thresheek)

Add "--enable-embed" to Debian-based CLI variants

---

apply-templates.sh
generate-stackbrew-library.sh
versions.json
versions.sh

Allow RC builds to come and go automatically as they become available (and disappear).
See also https://github.com/docker-library/docker/pull/332, https://github.com/docker-library/rabbitmq/pull/522, https://github.com/docker-library/mongo/pull/476, and https://github.com/docker-library/oi-janky-groovy/commit/3583ca5.
Closes #1248

Add RCs opportunistically

---

Dockerfile-linux.template
versions.json
versions.sh

They don't change within a release very often, so it doesn't feel "correct" to embed them in the block of more dynamic information we embed in `versions.json` (and IMO we get slightly better syntax this way).

Move GPG keys into the template

---

8.0/alpine3.14/zts/Dockerfile
8.0/alpine3.14/zts/docker-php-entrypoint
8.0/alpine3.14/zts/docker-php-ext-configure
8.0/alpine3.14/zts/docker-php-ext-enable
8.0/alpine3.14/zts/docker-php-ext-install
8.0/alpine3.14/zts/docker-php-source
8.0/alpine3.15/zts/Dockerfile
8.0/alpine3.15/zts/docker-php-entrypoint
8.0/alpine3.15/zts/docker-php-ext-configure
8.0/alpine3.15/zts/docker-php-ext-enable
8.0/alpine3.15/zts/docker-php-ext-install
8.0/alpine3.15/zts/docker-php-source
8.1/alpine3.14/zts/Dockerfile
8.1/alpine3.14/zts/docker-php-entrypoint
8.1/alpine3.14/zts/docker-php-ext-configure
8.1/alpine3.14/zts/docker-php-ext-enable
8.1/alpine3.14/zts/docker-php-ext-install
8.1/alpine3.14/zts/docker-php-source
8.1/alpine3.15/zts/Dockerfile
8.1/alpine3.15/zts/docker-php-entrypoint
8.1/alpine3.15/zts/docker-php-ext-configure
8.1/alpine3.15/zts/docker-php-ext-enable
8.1/alpine3.15/zts/docker-php-ext-install
8.1/alpine3.15/zts/docker-php-source
versions.json
versions.sh

#1075, but this time with proper gusto
Closes #1074

Add back 8-zts-alpine, take 2

---

7.4/alpine3.15/zts/Dockerfile
7.4/alpine3.16/zts/Dockerfile
7.4/bullseye/zts/Dockerfile
7.4/buster/zts/Dockerfile
8.0/alpine3.15/zts/Dockerfile
8.0/alpine3.16/zts/Dockerfile
8.0/bullseye/zts/Dockerfile
8.0/buster/zts/Dockerfile
8.1/alpine3.15/zts/Dockerfile
8.1/alpine3.16/zts/Dockerfile
8.1/bullseye/zts/Dockerfile
8.1/buster/zts/Dockerfile
8.2-rc/alpine3.15/zts/Dockerfile
8.2-rc/alpine3.16/zts/Dockerfile
8.2-rc/bullseye/zts/Dockerfile
8.2-rc/buster/zts/Dockerfile
Dockerfile-linux.template

Zend Signals are useless and cause segmentation faults when using ZTS:
* https://github.com/php/php-src/issues/9649#issuecomment-1264330874
* https://github.com/php/php-src/pull/5591#issuecomment-650064098
This patch disables Zend Signals for ZTS builds.

fix: disable Zend Signals for ZTS builds

---

7.4/alpine3.15/zts/Dockerfile
7.4/alpine3.16/zts/Dockerfile
8.0-rc/alpine3.15/zts/Dockerfile
8.0-rc/alpine3.16/zts/Dockerfile
8.0/alpine3.15/zts/Dockerfile
8.0/alpine3.16/zts/Dockerfile
8.1/alpine3.15/zts/Dockerfile
8.1/alpine3.16/zts/Dockerfile
8.2-rc/alpine3.15/zts/Dockerfile
8.2-rc/alpine3.16/zts/Dockerfile
Dockerfile-linux.template

The most popular use case of ZTS builds is to embed PHP in multithreaded programs such as [FrankenPHP](https://frankenphp.dev) or [NGINX Unit](https://unit.nginx.org/).
Unfortunately, generating libphp (which is necessary for this use case), is explicitly disabled for Alpine variants of the ZTS build.
This PR includes libphp in all ZTS builds (but not for the Alpine CLI variants, to keep the Alpine CLI image as small as possible).
Follows and fix https://github.com/docker-library/php/pull/1331#discussion_r1009984172.

feat: generate libphp for the Alpine variant of ZTS builds

---

8.0-rc/alpine3.16/fpm/Dockerfile
8.0-rc/bullseye/fpm/Dockerfile
8.0-rc/buster/fpm/Dockerfile
8.0/alpine3.16/fpm/Dockerfile
8.0/bullseye/fpm/Dockerfile
8.0/buster/fpm/Dockerfile
8.1-rc/alpine3.16/fpm/Dockerfile
8.1-rc/alpine3.17/fpm/Dockerfile
8.1-rc/bullseye/fpm/Dockerfile
8.1-rc/buster/fpm/Dockerfile
8.1/alpine3.16/fpm/Dockerfile
8.1/alpine3.17/fpm/Dockerfile
8.1/bullseye/fpm/Dockerfile
8.1/buster/fpm/Dockerfile
8.2-rc/alpine3.16/fpm/Dockerfile
8.2-rc/alpine3.17/fpm/Dockerfile
8.2-rc/bullseye/fpm/Dockerfile
8.2-rc/buster/fpm/Dockerfile
8.2/alpine3.16/fpm/Dockerfile
8.2/alpine3.17/fpm/Dockerfile
8.2/bullseye/fpm/Dockerfile
8.2/buster/fpm/Dockerfile
Dockerfile-linux.template

This should (finally) fix errors between FPM and NGINX (thanks @mfn!  sorry for the enormous delay in actually doing something :bow:).
Closes #878
I don't think we should merge this right away (especially not right before/during folks being off for the holidays), but I think this is probably the correct "final" answer for the NGINX 502 issues.

Add "fastcgi.logging = Off" to fpm defaults

---

8.0/alpine3.16/fpm/Dockerfile
8.0/bullseye/fpm/Dockerfile
8.0/buster/fpm/Dockerfile
8.1/alpine3.16/fpm/Dockerfile
8.1/alpine3.17/fpm/Dockerfile
8.1/bullseye/fpm/Dockerfile
8.1/buster/fpm/Dockerfile
8.2/alpine3.16/fpm/Dockerfile
8.2/alpine3.17/fpm/Dockerfile
8.2/bullseye/fpm/Dockerfile
8.2/buster/fpm/Dockerfile
Dockerfile-linux.template

See https://github.com/docker-library/php/issues/358#issuecomment-353686172.
:information_source: I didn't link the PR (https://github.com/php/php-src/pull/2310), because it is already linked in the PHP bug-report.

Add context to comment on php-fpm log-output

---

8.1/alpine3.16/zts/Dockerfile
8.1/alpine3.17/zts/Dockerfile
8.1/alpine3.18/zts/Dockerfile
8.1/bullseye/zts/Dockerfile
8.1/buster/zts/Dockerfile
8.2/alpine3.17/zts/Dockerfile
8.2/alpine3.18/zts/Dockerfile
8.2/bullseye/zts/Dockerfile
8.2/buster/zts/Dockerfile
Dockerfile-linux.template

https://github.com/php/php-src/pull/10141 has just been merged. It fixes timeout support for ZTS builds on Linux.
This feature will be enabled by default in PHP 8.3. It hasn't been in previous version because it introduces an ABI break, but it's not a big issue when using the Docker images because the extensions are usually compiled against the local version of PHP. This patch enables this fix.

enable Max Execution Timers for ZTS builds

---

8.1-rc/bookworm/apache/Dockerfile
8.1/bookworm/apache/Dockerfile
8.2-rc/bookworm/apache/Dockerfile
8.2/bookworm/apache/Dockerfile
8.3-rc/bookworm/apache/Dockerfile
8.3/bookworm/apache/Dockerfile
Dockerfile-linux.template

See https://salsa.debian.org/apache-team/apache2/-/commit/b97ca8714890ead1ba6c095699dde752e8433205
Fixes #1444

Fix permissions on $APACHE_RUN_DIR/socks in Debian Bookworm+

---

Dockerfile-linux.template

> DOCKER_PHP_ENABLE_DEBUG is not used or supported by official-images; this is for users who want to build their own php image with debug enabled
This will allow power users to generate their own PHP Dockerfiles with debug enabled. This is explicitly written to not change the regular versions of the Dockerfiles (i.e. running `./apply-templates.sh` will result in no change). I have build tested one or two versions and they seem to work:
```console
$ docker build 8.0/alpine3.16/cli/
...
Successfully built 7feb88eade75
$ docker run -it --rm 7feb88eade75 php -i
...
Debug Build => yes
...
```
To regenerate all the Dockerfiles with debug enabled (`bash`, `jq`, `gawk`, and `wget` are required to run it):
```console
$ DOCKER_PHP_ENABLE_DEBUG=1 ./apply-templates
processing 8.0/bullseye/cli ... …
```

Add template support for "--enable-debug" flag

---

Dockerfile-linux.template

This reverts the (temporary) changes introduced in !1526. Now that the next alpha is released, they are no longer required and have served their purpose well ;)

Remove patch workaround for 8.4.0alpha1

---

Dockerfile-linux.template

The end result is the same, but the construction is more ergonomic.
See also https://github.com/docker-library/buildpack-deps/pull/165 (and linked)

Use jq's `IN()` instead of `index()`

---

generate-stackbrew-library.sh

Because of the errors seen in https://github.com/docker-library/php/issues/1585, many of the DOI images will not build successfully on Alpine 3.22. Given the near end-of-life nature of PHP 8.1, it seems unlikely that a fix will come.
All of the current failing builds (`joomla`, `mediawiki`, `wordpress`) rely on the default Alpine version (correctly or incorrectly).  For the one we directly maintain (`wordpress`), we don't have a concept of following a specific Alpine version, and I figured this would be the easier/faster fix.
These are all from `php:8.1-*alpine` and so will be fixed by staying on Alpine 3.21 (until PHP 8.1 is end of life)
- [joomla:4.4.13-php8.1-fpm-alpine](https://github.com/joomla-docker/docker-joomla/blob/2b32f0a2ba4ad99f15c0acd26b2f862c038ff3f5/4.4/php8.1/fpm-alpine/Do …

Change default Alpine image for 8.1

---

8.5-rc/alpine3.21/cli/Dockerfile
8.5-rc/alpine3.21/fpm/Dockerfile
8.5-rc/alpine3.21/zts/Dockerfile
8.5-rc/alpine3.22/cli/Dockerfile
8.5-rc/alpine3.22/fpm/Dockerfile
8.5-rc/alpine3.22/zts/Dockerfile
8.5-rc/bookworm/apache/Dockerfile
8.5-rc/bookworm/cli/Dockerfile
8.5-rc/bookworm/fpm/Dockerfile
8.5-rc/bookworm/zts/Dockerfile
8.5-rc/bullseye/apache/Dockerfile
8.5-rc/bullseye/cli/Dockerfile
8.5-rc/bullseye/fpm/Dockerfile
8.5-rc/bullseye/zts/Dockerfile
Dockerfile-linux.template
versions.json

Manually because `opcache` now no longer exists.

Update to 8.5.0alpha4
