docker-library/php

5.4/Dockerfile
5.4/apache/Dockerfile
5.4/fpm/Dockerfile
5.5/Dockerfile
5.5/apache/Dockerfile
5.5/fpm/Dockerfile
5.6/Dockerfile
5.6/apache/Dockerfile
5.6/fpm/Dockerfile

Install file and re2c as required by docker-php-ext-install

---

5.4/Dockerfile
5.4/apache/Dockerfile
5.4/fpm/Dockerfile
5.5/Dockerfile
5.5/apache/Dockerfile
5.5/fpm/Dockerfile
5.6/Dockerfile
5.6/apache/Dockerfile
5.6/fpm/Dockerfile

As per latest security updates from php.net

Update to PHP 5.4.41, 5.5.25 and 5.6.9

---

5.4/Dockerfile
5.4/apache/Dockerfile
5.4/fpm/Dockerfile
5.5/Dockerfile
5.5/apache/Dockerfile
5.5/fpm/Dockerfile
5.6/Dockerfile
5.6/apache/Dockerfile
5.6/fpm/Dockerfile

Update announcement:
http://php.net/archive/2015.php#id2015-08-06-4
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

Update PHP 5.6.12, 5.5.28 and 5.4.44

---

5.4/fpm/php-fpm.conf
5.5/fpm/php-fpm.conf
5.6/fpm/php-fpm.conf
7.0/fpm/php-fpm.conf

Ensure PHP-FPM worker stdout and stderr are sent to the main error log.

---

7.0/Dockerfile
7.0/apache/Dockerfile
7.0/fpm/Dockerfile

All is in the title :)
Here the changelog : http://nl1.php.net/ChangeLog-7.php#7.0.1

Upgrade to 7.0.1

---

docker-php-ext-enable

Fixes #173
cc @strarsis -- would you like to give this a try and make sure it works? :smile:

Add "--ini-name" flag to docker-php-ext-enable (especially for controlling order)

---

5.5/Dockerfile
5.5/apache/Dockerfile
5.5/fpm/Dockerfile
5.5/zts/Dockerfile
5.6/Dockerfile
5.6/apache/Dockerfile
5.6/fpm/Dockerfile
5.6/zts/Dockerfile
7.0/Dockerfile
7.0/apache/Dockerfile
7.0/fpm/Dockerfile
7.0/zts/Dockerfile

See also docker-library/official-images#1420.

Fix "gpg" usage to stop relying on deprecated and insecure behavior

---

5.5/apache/Dockerfile
5.6/apache/Dockerfile
7.0/apache/Dockerfile
apache-Dockerfile-block-1

Fix "AllowOverride" and "Indexes" defaults

---

5.6/apache/Dockerfile
7.0/apache/Dockerfile
apache-Dockerfile-block-1

Mmm. Lost a planet, Master Obi-Wan has. How embarrassing. How embarrassing. :open_mouth:

Fix sed to modify the envvars file

---

5.6/Dockerfile
5.6/alpine/Dockerfile
5.6/apache/Dockerfile
5.6/fpm/Dockerfile
5.6/fpm/alpine/Dockerfile
5.6/zts/Dockerfile
5.6/zts/alpine/Dockerfile
7.0/Dockerfile
7.0/alpine/Dockerfile
7.0/apache/Dockerfile
7.0/fpm/Dockerfile
7.0/fpm/alpine/Dockerfile
7.0/zts/Dockerfile
7.0/zts/alpine/Dockerfile
Dockerfile-alpine.template
Dockerfile-debian.template
update.sh

Closes #138
:+1: @ericandrewlewis

Use "https" for communications with "php.net" where possible

---

5.6/alpine/Dockerfile
5.6/fpm/alpine/Dockerfile
5.6/zts/alpine/Dockerfile
7.0/alpine/Dockerfile
7.0/fpm/alpine/Dockerfile
7.0/zts/alpine/Dockerfile
7.1/alpine/Dockerfile
7.1/fpm/alpine/Dockerfile
7.1/zts/alpine/Dockerfile
Dockerfile-alpine.template

Reverts docker-library/php#357
See https://github.com/docker-library/golang/pull/131#issuecomment-270677556 for more discussion on this issue. :disappointed:

Revert "Upgrade alpine to v3.5"

---

5.6/jessie/apache/Dockerfile
5.6/jessie/cli/Dockerfile
5.6/jessie/fpm/Dockerfile
5.6/jessie/zts/Dockerfile
7.0/jessie/apache/Dockerfile
7.0/jessie/cli/Dockerfile
7.0/jessie/fpm/Dockerfile
7.0/jessie/zts/Dockerfile
7.1/jessie/apache/Dockerfile
7.1/jessie/cli/Dockerfile
7.1/jessie/fpm/Dockerfile
7.1/jessie/zts/Dockerfile
7.2-rc/stretch/apache/Dockerfile
7.2-rc/stretch/cli/Dockerfile
7.2-rc/stretch/fpm/Dockerfile
7.2-rc/stretch/zts/Dockerfile
Dockerfile-debian.template

See https://github.com/docker-library/python/issues/236 for details.

Swap from "gnupg2" to "gnupg"

---

7.3/alpine3.8/fpm/Dockerfile
7.3/stretch/fpm/Dockerfile
fpm-Dockerfile-block-2
update.sh

see comment https://github.com/docker-library/php/pull/725#issuecomment-443540114

Increase log limit

---

update.sh

Closes #808
Thanks @khs1994 for pointing out that https://www.php.net works now! :+1:

Swap "secure.php.net" for "www.php.net" (now that it supports https properly)

---

7.1/alpine3.10/cli/Dockerfile
7.1/alpine3.10/fpm/Dockerfile
7.1/alpine3.10/zts/Dockerfile
7.1/alpine3.9/cli/Dockerfile
7.1/alpine3.9/fpm/Dockerfile
7.1/alpine3.9/zts/Dockerfile
7.2/alpine3.10/cli/Dockerfile
7.2/alpine3.10/fpm/Dockerfile
7.2/alpine3.10/zts/Dockerfile
7.2/alpine3.9/cli/Dockerfile
7.2/alpine3.9/fpm/Dockerfile
7.2/alpine3.9/zts/Dockerfile
7.3/alpine3.10/cli/Dockerfile
7.3/alpine3.10/fpm/Dockerfile
7.3/alpine3.10/zts/Dockerfile
7.3/alpine3.9/cli/Dockerfile
7.3/alpine3.9/fpm/Dockerfile
7.3/alpine3.9/zts/Dockerfile
7.4-rc/alpine3.10/cli/Dockerfile
7.4-rc/alpine3.10/fpm/Dockerfile
7.4-rc/alpine3.10/zts/Dockerfile
Dockerfile-alpine.template

```console
$ bashbrew build ...
...
+ dpkg-architecture --query DEB_BUILD_GNU_TYPE
+ gnuArch=s390x-linux-musl
+ test s390x-linux-musl '=' s390x-linux-gnu
```

Update s390x test to the proper dpkg-architecture value

---

7.2/stretch/apache/Dockerfile
7.2/stretch/cli/Dockerfile
7.2/stretch/fpm/Dockerfile
7.2/stretch/zts/Dockerfile
7.3/stretch/apache/Dockerfile
7.3/stretch/cli/Dockerfile
7.3/stretch/fpm/Dockerfile
7.3/stretch/zts/Dockerfile
Dockerfile-debian.template

Properly pin all buster dists in stretch-based images

---

8.0-rc/alpine3.12/zts/Dockerfile
8.0-rc/alpine3.12/zts/docker-php-entrypoint
8.0-rc/alpine3.12/zts/docker-php-ext-configure
8.0-rc/alpine3.12/zts/docker-php-ext-enable
8.0-rc/alpine3.12/zts/docker-php-ext-install
8.0-rc/alpine3.12/zts/docker-php-source

It would appear that https://github.com/docker-library/php/pull/1028#issuecomment-649763859 is fixed now! :+1:
Closes #1074

Add back 8-zts-alpine

---

8.0/alpine3.12/cli/Dockerfile
8.0/alpine3.12/fpm/Dockerfile
8.0/buster/apache/Dockerfile
8.0/buster/cli/Dockerfile
8.0/buster/fpm/Dockerfile
8.0/buster/zts/Dockerfile
Dockerfile-alpine.template
Dockerfile-debian.template

Turns out we missed this minor bit in #1088 :sweat_smile:

Keep "pecl update-channels" for 8.0 also

---

Dockerfile-linux.template

Clean up handling of `--enable-ftp`

---

8.1/alpine3.18/cli/Dockerfile
8.1/alpine3.18/fpm/Dockerfile
8.1/alpine3.18/zts/Dockerfile
8.1/alpine3.19/cli/Dockerfile
8.1/alpine3.19/fpm/Dockerfile
8.1/alpine3.19/zts/Dockerfile
8.1/bookworm/apache/Dockerfile
8.1/bookworm/cli/Dockerfile
8.1/bookworm/fpm/Dockerfile
8.1/bookworm/zts/Dockerfile
8.1/bullseye/apache/Dockerfile
8.1/bullseye/cli/Dockerfile
8.1/bullseye/fpm/Dockerfile
8.1/bullseye/zts/Dockerfile
versions.json

https://github.com/docker-library/php/pull/1505, part two

Update to 8.1.28 (security release)
